# render.yaml

services:
  - type: web
    name: react-videocall
    runtime: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: .
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - yarn.lock
